Feature/get point of intersection for lines AND work in DistanceCalculators
gems-development/geos-gempix pull request #11
Opened 2022-11-19 16:08 UTC by AnastasiaKallisto

Интегрировала Contour в DistanceCalculators и исправила методы в классах пересечения.

2022-11-21 06:43 UTC, ddolgushin requested changes

2022-11-21 06:43 UTC, ddolgushin commented on GeometryModels/Visitors/Intersectors/LineIntersector.cs
> +            double A1 = lineEq1[0], B1 = lineEq1[1], C1 = lineEq1[2],
Локальные переменные лучше называть в нижнем регистре.

2022-11-22 04:03 UTC, vivlav commented on GeometryModels/Visitors/DistanceCalculators/ModelsDistanceCalculator/LineDistanceCalculator.cs
> +            else return 0;
Здесь тоже лучше инвертировать `if`

2022-11-22 08:30 UTC, vivlav commented on GeometryModels/Visitors/Intersectors/LineIntersector.cs
> +        internal static Point? GetPointOfIntersection(double[] lineEq1, double[] lineEq2)
Стоит заменить массив на набор параметров (можно использовать именной кортеж), но массив фиксированной длины - не очень читаем.

2022-11-22 08:30 UTC, vivlav approved these changes

2022-11-25 04:11 UTC, ddolgushin approved these changes

2022-11-25 04:11 UTC, merged

2022-11-30 02:45 UTC, vivlav commented on GeometryModels/Visitors/Insiders/ContourInsider.cs
> +        internal static double[] GetEquationOfBisector((double a1, double b1, double c1) lineEq1,
Лучше использовать `(a, b, c)` индекс в переменной `lineEq1`

2022-11-30 02:45 UTC, vivlav commented on GeometryModels/Visitors/Insiders/ContourInsider.cs
> +            double a2 = lineEq1.b1;
тут и ниже явно ошибка с буквами, `a` - присваивается `b`.

2022-11-30 02:45 UTC, vivlav commented on GeometryModels/Visitors/Intersectors/LineIntersector.cs
> +                y = -c1 / b1;
а что если `b1==0`?