Add checks into searchers
gems-development/geos-gempix pull request #27
Opened 2023-02-22 10:20 UTC by DenisKamaliev

2023-02-22 16:56 UTC, AnastasiaKallisto requested changes
Маленькая поправочка и можно мерджить, кинешь ссылку в беседу, когда удалишь строчку. P.S. Позже эти проверки изменятся, так как добавится новый класс, в котором будут очень конкретные, не рекурсивные, понятные проверки, и пользоваться мы будем ими.

2023-02-22 16:56 UTC, AnastasiaKallisto commented on GeosGempix/Visitors/ShortestLineSearchers/ModelsShortestLineSearcher/ContourShortestLineSearcher.cs
>              Insider insider = new Insider(contour, point);
Убрать 67 строчку, комментарии как в 66 строке НЕ УБИРАТЬ

2023-03-01 08:15 UTC, AnastasiaKallisto approved these changes
Готово (это первая версия, в которой нужно будет заменить проверки на более точные)

2023-03-01 11:45 UTC, vivlav commented on GeosGempix/Visitors/ShortestLineSearchers/MultiModelsShortestLineSearcher/MultiLineShortestLineSearcher.cs
>              MultiLine multiLine,
параметры метода (даже `Func`) - должны быть с маленькой буквы.  тонла `GetShortestLine.Invoke(line, primitive)` можно заменить без проблем на `getShortestLine(line, primitive)`

2023-03-01 11:45 UTC, vivlav commented on GeosGempix/Visitors/ShortestLineSearchers/MultiModelsShortestLineSearcher/MultiLineShortestLineSearcher.cs
>              MultiLine multiLine,
Это еще чуть меньше путать будет

2023-03-01 11:45 UTC, vivlav commented on GeosGempix/Visitors/ShortestLineSearchers/ModelsShortestLineSearcher/PolygonShortestLineSearcher.cs
> +        foreach (Contour contour in polygon1.GetHoles()){
вместо точного указания `Contour` лучше использовать `var` - это чуть делает код чуть читабельнее., а рефакторинги проще.

2023-03-01 11:45 UTC, vivlav commented on GeosGempix/Visitors/ShortestLineSearchers/ModelsShortestLineSearcher/PolygonShortestLineSearcher.cs
> +        foreach (Contour contour in polygon1.GetHoles()){
Название должно быть hole, а не `contour`

2023-03-02 09:01 UTC, merged