HelpMethodsInVisitors Добавил методы в ContourDistanceCalculator, Con…
gems-development/geos-gempix pull request #35
Opened 2023-03-03 10:10 UTC by DenisKamaliev

…tourInsider, ContourIntersector,PolygonIntersector,MultiPolygonIntersector

Осталось добавить в PolygonInsider,MultiPolygonInsider

2023-03-03 11:04 UTC, AnastasiaKallisto requested changes
В Insider и Intersector всё наоборот... Сейчас будет коммит, обрати на него внимание, пожалуйста

2023-03-03 11:04 UTC, AnastasiaKallisto commented on GeosGempix/Visitors/DistanceCalculators/ModelsDistanceCalculator/ContourDistanceCalculator.cs
> +            double result = 0;
result = double.maxValue, здесь и везде

2023-03-03 11:04 UTC, AnastasiaKallisto commented on GeosGempix/Visitors/Insiders/ContourInsider.cs
> +            return IsInside(contour, point) && !ContourIntersector.IntersectsBorders(contour, point);
Должно быть ровным счетом наоборот. В методе IsStrictlyInside - большой кусок кода, скопируй его из IsInside. А в методе IsInside будет маленький кусок, в котором будет вызов IsStriclyInside и чего-нибудь еще.

2023-03-15 07:27 UTC, AnastasiaKallisto requested changes
Нужны еще поправки и дополнительные функции.

2023-03-15 07:27 UTC, AnastasiaKallisto commented on GeosGempix/Visitors/Insiders/PolygonInsider.cs
>              if (MultiLineIntersector.Intersects(multiLine, polygon))
IntersectsBorders, здесь и везде в strictlyInside.
Если фигура пересекает границы, значит она не внутри.
Если она просто пересекает, значит, она может быть и внутри, и пересекать границы, и касаться их, в общем, просто имеет общие точки.

2023-03-15 07:27 UTC, AnastasiaKallisto commented on GeosGempix/Visitors/Intersectors/ContourIntersector.cs
>                  if (LineIntersector.Intersects(line, point))
Лучше поставь IntersectsBorders, чтобы с толку не сбивало. В методах IntersectsBorders не должно быть вызовов функций Intersects, даже если они для отрезков вызываются и вроде как одно и то же.

2023-03-15 07:27 UTC, AnastasiaKallisto commented on GeosGempix/Visitors/Insiders/ContourInsider.cs
>              return IsInside(contour, line1.Point1) && !ContourIntersector.IntersectsBorders(contour, line1);
в IsStrictlyInside не должно быть вызовов IsInside, только IsStrictlyInside, даже если суть одна и та же. Как минимум отлаживать проще, нет лишнего прыжка через функцию.

2023-03-15 07:27 UTC, AnastasiaKallisto commented on GeosGempix/Visitors/Insiders/ContourInsider.cs
>          {
Кстати, тут двойная проверка намечается. И не только тут. 
Представь, что мы вызвали функцию (переименуй в ней line1 в line, и вообще везде где не нужна эта цифорка)
internal static bool Intersects(Contour contour, Line line1)
        {      
            if (IntersectsBorders(contour, line1))
                    return true;
            if (ContourInsider.IsStrictlyInside(contour, line1))
                return true;
            return false;
        }
Она проверила, не пересекаем ли мы границы, и отправила нас сюда, в IsStrictlyInside(Contour contour, Line line) (переименуй кстати, line1 в line), где мы снова вызываем IntersectsBorders. Это не рекурсия, но дважды вызывается одна и та же проверка IntersectsBorders.
Предлагаю создать еще одну пачку функций IsStrictlyInside, но с другой сигнатурой. Чтобы она принимала на вход флаг doesIntersectBorders.
IsStrictlyInside (Contour contour, Line line, boolean doesIntersectsBorders)
Таким образом, функция в интерсекторе перепишется вот так:
internal static bool Intersects(Contour contour, Line line)
        {      
            if (IntersectsBorders(contour, line))
                    return true;
            if (ContourInsider.IsStrictlyInside(contour, line, false))
                return true;
            return false;
        }

А новая функция будет выглядеть также, но без доп проверки на пересечение границ.
IsStrictlyInside (Contour contour, Line line, boolean doesIntersectsBorders) {
        if (!doesIntersectsBorders) {
              return IsStrictlyInside(contour, line.Point1);
        } else 
              return false;
}

Текущие функции IsStrictlyInside оставь, они нормальные вроде, но нужны дополнительные, для более быстрой работы интерсектора.

2023-03-15 07:27 UTC, AnastasiaKallisto commented on GeosGempix/Visitors/Insiders/ContourInsider.cs
> +            throw new NotImplementedException();
Можешь попробовать прописать одну вот эту проверку. По крайней мере, надо начинать о ней думать (потому что еще предстоит писать касатель).
Одни из мудреных картинок, которые мне пришли в голову, на рисунке. Но, конечно, можно придумать еще много всяких разных.
Мне в голову приходил вариант проверять точки "чуть левее" всех точек пересечения, и "чуть правее". То есть нужно получить уравнение прямой, и подставить туда x-double.Min и x+double.Min, а если отрезок вертикальный(это надо проверять) и о смещениях Х не может быть и речи, то то же самое с Y. Если они обе внутри, значит, все хорошо. Если какая-то из них снаружи, значит, фигура уже не внутри.
Обращу также внимание на то, что эти точки "плюс-минус чуть-чуть" должны принадлежать отрезку. 
Если одна из них не принадлежит, надо посмотреть, какая именно. Может, отрезок как раз вершиной касается, пойдем чуть влево - мы все еще не отрезке и находимся внутри, пойдем чуть вправо - мы вообще из отрезка вылетели и проверять это нет смысла. В итоге точка проверку прошла.
И наоборот, мы можем касаться отрезком снаружи. Чуть влево - мы вылетели с отрезка. Чуть вправо - мы на отрезке, но находимся снаружи, значит проверку не прошли, выходим из функции с false.
Здесь предстоит нещадно эксплуатировать функцию "получить точку пересечения". У контура много сторон, и придется проверять каждую. Но, что радует, у каждой стороны может быть либо одна точка пересечения, либо уравнения отрезка и стороны совпадают, но тогда все равно крайние точки проверять надо, не вылетели ли за пределы стороны.
![image](https://user-images.githubusercontent.com/78430177/225233643-9df2a033-6a2c-4356-86e8-eba88fd3a2e3.png)

2023-03-19 15:57 UTC, DenisKamaliev commented on GeosGempix/Visitors/Intersectors/ContourIntersector.cs
>                  if (LineIntersector.Intersects(line, point))
у линии нет функции intersectsBorders, да и какой в ней смысл? у линии нет площади, следственно и границ нет

2023-03-31 09:57 UTC, AnastasiaKallisto requested changes
1) Помимо этих 4 комментов, посмотрела последний коммит "исправил конфликты"
Файлов .cs.orig быть не должно, их нужно удалить.
Также, обрати внимание, что этот коммит не компилируется. Исправления там не сильно страшные, поправь, пожалуйста.
![image](https://user-images.githubusercontent.com/78430177/229089175-bdb7c6e0-9152-4094-9c6f-31bd27f048a8.png)

2023-03-31 09:57 UTC, AnastasiaKallisto commented on GeosGempix/Visitors/DistanceCalculators/ModelsDistanceCalculator/ContourDistanceCalculator.cs
> +            List<Line> lines = new List<Line>();
В контуре есть метод GetLines()

2023-03-31 09:57 UTC, AnastasiaKallisto commented on GeosGempix/Visitors/DistanceCalculators/ModelsDistanceCalculator/ContourDistanceCalculator.cs
> +                    result = distance;
if (distance < result)
{
if (distance == 0) 
    return 0;
result = distance;
}
Есть еще такой ньюанс, что не факт, что там чистый ноль вылезет. Возможно нужно eps, причем очень маленькое.
double eps=0.(сколько-то нулей?)1;
if(fabs(i)<eps){//считаем, что он равен нулю
//...
}

2023-03-31 09:57 UTC, AnastasiaKallisto commented on GeosGempix/Visitors/DistanceCalculators/ModelsDistanceCalculator/ContourDistanceCalculator.cs
> +        internal static double GetDistanceToInnerPoint(Contour contour, Point point)
Непонятно, проверял кто-то или нет, что точка действительно внутри. Думаю, тут должна быть та же самая история с флагом checkRequired

2023-03-31 09:57 UTC, AnastasiaKallisto commented on GeosGempix/Visitors/Insiders/ContourInsider.cs
> +
Убрать комменты и строку "throw ..."
Остальные методы ты исправил, значит, эта пояснялка больше не нужна

2023-04-05 08:44 UTC, DenisKamaliev commented on GeosGempix/Visitors/DistanceCalculators/ModelsDistanceCalculator/ContourDistanceCalculator.cs
> +        internal static double GetDistanceToInnerPoint(Contour contour, Point point)
Мне кажется, что в этом нет смысла, т.к. само название функции говорит о том, что она вызывается в случае, если точка внутри

2023-04-05 15:35 UTC, ddolgushin approved these changes

2023-04-05 16:03 UTC, ddolgushin approved these changes

2023-04-05 16:22 UTC, AnastasiaKallisto approved these changes

2023-04-05 16:22 UTC, merged