Добавление проверок для касателя, рефакторинг тестов
gems-development/geos-gempix pull request #60
Opened 2023-04-28 11:11 UTC by d21eagle

2023-04-28 11:23 UTC, ddolgushin requested changes

2023-04-28 11:23 UTC, ddolgushin commented on GeosGempix.Tests/IntersectorTest/PolygonIntersectorTests.cs
> +    public static IEnumerable<object[]> Data1 =>
Это и подобные свойства, хранящие тестовые данные, лучше делать приватными и называть говорящими именами, например, `PolygonAndMultipolygonIntersectionTestData`.

2023-04-28 15:39 UTC, d21eagle commented on GeosGempix.Tests/IntersectorTest/PolygonIntersectorTests.cs
> +    public static IEnumerable<object[]> Data1 =>
Судя по всему свойства в xunit должны быть публичными, в ином случае System.NotSupportedException

2023-05-03 03:18 UTC, ddolgushin approved these changes

2023-05-03 03:18 UTC, merged